@startuml Class Diagram

skin rose
skinparam classAttributeIconSize 0
' skinparam linetype ortho
skinparam linetype polyline
hide circle
scale 3

class LoaiXeDap {
    - id: int
    - tenXe: string
    - dongXe: string
    - nuocSanXuat: string
}

class PhieuNhapXeDap{
    - id: int
    - ngayNhap: date
    - giaNhap: string
    - hienTrang: string 
}


class DayKho {
    - id: int
    - soLuotTrong: int
    - soLuongChua: int
}

class XeDap {
    - id: int
    - idLoaiXeDap: int
    - idNhapXeDap: int
    - idDay: int
    - trangThai: string
    - mucGia: int
}

class PhieuDatMua {
    - id: int
    - idXe: int
    - ngayNhan: date
    - hinhThucGiaoHang: string
    - diaChi: string
}

class PhieuMuaHang {
    - id: int
    - idXe: int
    - ngayNhan: date
    - hinhThucGiaoHang: string
    - diaChi: string
}

class HoaDon {
    - id: int
    - ngayBan: date
}

class ChiTietHoaDon {
    - id: int
    - idHoaDon: int
    - idXe: int
    - soLuong: int
}

class PhieuDangKiDoiTra {
    - id: int
    - idKhachHang: int
    - tenSanPham: string
    - moTaHienTrang: string
    - linkHinhMinhHoa: string
    - hinhThucDoiTra: string
    - idXeMuonDoi: int
}

class ThongTinChoThue {
    - id: int
    - idKhachHang: int
    - idXeChoThue: int
    - ngayNhanXe: date
    - soNgayThue: int
    - linkAnhChupCCCD: string
    - chiPhiSuaChua: int
}

class ThongTinKhachHang{
    - id: int
    - tenTaiKhoan: string
    - matKhau: string
    - diaChi: string
    - soDiemTich: int
}


LoaiXeDap <|-- XeDap
ChiTietHoaDon "*"--*"1" HoaDon
PhieuNhapXeDap "1"--"*" XeDap
DayKho "1"--"*" XeDap
XeDap "1"--"*" ChiTietHoaDon
XeDap "1"--"*" PhieuDangKiDoiTra
ThongTinKhachHang "1"--"*" PhieuDangKiDoiTra
XeDap "1"--"*" PhieuMuaHang
XeDap "1"--"*" PhieuDatMua
ThongTinChoThue "*"--"1" ThongTinKhachHang
ThongTinChoThue "*"--"1" XeDap









@enduml