@startuml SequenceDiagram

skin rose
hide footbox

title Mua xe trực tiếp

actor NhanVien
boundary ":User Interface\nClass" as ui
control ":Xe Controller\nClass" as xeControl
control ":KhachHang Controller\nClass" as khControl
control ":HoaDon Controller\nClass" as hdControl
control ":PhieuMuaXe Controller\nClass" as pmxControl
entity ":Xe Entity\nClass" as xe
entity ":KhachHang Entity\nClass" as kh
entity ":HoaDon Entity\nClass" as hd
entity ":PhieuMuaXe Entity\nClass" as pmx

autonumber
NhanVien++
NhanVien -> ui++ : Tạo phiếu mua xe
ui -> pmxControl++ : Gửi yêu cầu tạo phiếu mua xe
pmxControl -> pmx++ : Tạo phiếu mua xe
pmx --> pmxControl-- : Trả về phiếu mua xe
pmxControl --> ui-- : Trả về phiếu mua xe
ui --> NhanVien : Hiển thị phiếu mua xe
NhanVien -> ui : Nhập thông tin hóa đơn
ui -> hdControl++ : Gửi yêu cầu tạo hóa đơn
hdControl -> hd++ : Tạo hóa đơn
hd --> hdControl-- : Trả về hóa đơn
hdControl --> ui-- : Trả về hóa đơn
ui --> NhanVien : Hiển thị hóa đơn
alt Khách hàng mua lần đầu
    NhanVien -> ui : Nhập thông tin khách hàng
    ui -> khControl++ : Gửi yêu cầu tạo khách hàng
    khControl -> kh++ : Tạo khách hàng
    kh --> khControl-- : Trả về thông tin khách hàng
    khControl --> ui-- : Trả về thông tin khách hàng
    ui --> NhanVien : Hiển thị thông tin khách hàng
end
NhanVien -> ui : Chọn khách hàng và cập nhật thanh toán
ui -> pmxControl++ : Gửi yêu cầu cập nhật phiếu mua xe
pmxControl -> pmx++ : Cập nhật phiếu mua xe
pmx --> pmxControl-- : Trả về thông báo
par
    pmxControl -> xeControl++ : Gửi yêu cầu cập nhật số lượng xe
    pmxControl++
    xeControl -> xe++ : Cập nhật số lượng xe
    xe --> xeControl-- : Trả về thông báo
    xeControl--> pmxControl-- : Trả về thông báo
    else
    autonumber 23
    pmxControl -> khControl++ : Gửi yêu cầu cập nhật thông tin tích điểm
    khControl -> kh++ : Cập nhật thông tin tích điểm
    kh --> khControl-- : Trả về thông báo
    khControl--> pmxControl-- : Trả về thông báo
    pmxControl--
end
pmxControl --> ui-- : Trả về thông báo
ui --> NhanVien : Hiển thị phiếu mua xe

@enduml