@startuml MyBicycle
skin rose
left to right direction

actor "Chủ của hàng" as owner
actor "Khách hàng" as customer
actor "Nhân viên" as staff

rectangle MyBicycle {
    usecase "Trưng bày" as trungBay
    usecase "Nhập xe" as nhapXe
    usecase "Bán xe" as banXe
    usecase "Thuê xe" as thueXe
    usecase "Đặt mua xe" as muaXe
    usecase "Đổi trả xe" as doiTraXe
    ' usecase "Trả xe" as traXe
    ' usecase "Đổi xe" as doiXe
    usecase "Đăng nhập" as dangNhap
    usecase "Đăng ký" as dangKy
    usecase "Tạo phiếu mua hàng" as taoPhieuMuaHang
    usecase "Tạo hóa đơn" as taoHoaDon
    usecase "Cất kho" as catKho
    usecase "Nhập nhiều xe" as nhapNhieuXe
    usecase "Tích điểm" as tichDiem
    
}

owner ---> (nhapXe)
(nhapXe) ..> (catKho): <<include>>
(nhapXe) <.. (nhapNhieuXe): <<extend>>
owner ---> (trungBay)
(trungBay) <.. (catKho): <<extend>>

' (taoPhieuMuaHang) <.. (muaXe): <<include>>
(thueXe) <-- customer
(taoHoaDon) <.. (thueXe): <<include>>
(taoHoaDon) <. (tichDiem): <<include>>
(muaXe) <--- customer
(doiTraXe) <-- customer
(catKho) ..> (doiTraXe): <<extend>>
(taoHoaDon) ..> (doiTraXe): <<extend>>
(dangKy) <--- customer
(dangNhap) <--- customer

(taoPhieuMuaHang) -[hidden]-> (muaXe)
(taoPhieuMuaHang) -[hidden]-> (dangNhap)
(taoPhieuMuaHang) -[hidden]-> (dangKy)

staff --> (banXe)
(banXe) ..> (taoPhieuMuaHang): <<include>>
(banXe) ..> (taoHoaDon): <<include>>




@enduml