@startuml ProjectStateDiagram
skin rose
hide empty description

title Project State

[*] --> Draft : Created project
Draft --> UnderReview : Confirmed
Draft --> Discarded : Cancelled
UnderReview --> Discarding: Discarded project
UnderReview --> Updating : Updated project
Updating --> UnderReview : Completed update
Discarding --> Discarded : Confirmed
Discarding --> UnderReview : Cancelled
UnderReview --> ReadyToBeRegistered : Reviewed
ReadyToBeRegistered --> Registered : Registered project
Registered --> InProgress : Implemented project
InProgress --> Completed : Completed project
InProgress --> OnHold : Put project\non hold
OnHold --> InProgress : Resumed project
Discarded --> [*]
Completed --> [*]

state Updating {
    [*] --> Updated : Confirmed
    Updated --> [*]
    [*] --> Unupdated : Cancelled
    Unupdated --> [*]
}
@enduml