@startuml UC Main
skin rose 
left to right direction
actor Admin as a
actor Student as s
actor "Academic affair" as aff
actor Teacher as t
rectangle "Project Management System" {
  usecase "Manage account" as ManageAccount <<CRUD>>
  usecase "Manage analyze&report infomation" as ManageAnalyze
  usecase "Export score table" as ExportScoreTable
  usecase "Manage announcement" as ManageNotes <<CRUD>>
  usecase "Manage project" as ManageProject <<CRUD>>
  usecase "Sign in" as Signin
  usecase "View score" as ViewScore
  usecase "Manage profile" as ManageProfile
  usecase "View announcement" as ViewNotes
  usecase "Update score" as UpdateScore
  usecase "Register project" as RegisterProject
  usecase "Unregister project" as UnregisterProject
  usecase "Manage register time" as ManageRegisterTime <<CRUD>>
}

a -- ManageAccount
Signin --- s
ManageProfile --- s
aff ----- ManageProfile
ManageProfile --- t
aff -- ManageAnalyze
aff -- ManageNotes
ManageNotes ----- t
aff -----ManageProject
RegisterProject --- s
UnregisterProject --- s
ManageProject ----- t
ViewNotes --- s
aff ----- ViewScore
ViewScore --- s
UpdateScore ----- t
ViewScore ----- t
Signin ----- t
aff ----- Signin
aff -- ExportScoreTable
aff ----- ManageRegisterTime
ExportScoreTable ----- t
ManageRegisterTime ----- t
@enduml