@startuml UC Main
skin rose 
left to right direction

' skinparam Linetype polyline

actor Admin as a
actor Student as s
actor "Academic affair" as aa
actor Teacher as t
rectangle "Project Management System" {
  usecase "Manage account" as ManageAccount

  usecase "Manage announcement" as ManageAnnouncement
  usecase "Manage project" as ManageProject

  usecase "Manage registered project" as ManageRegistered
  usecase "Manage profile" as ManageProfile
  usecase "Manage score" as ManageScore
  
  usecase "Manage authorization" as ManageAuthorization
  usecase "Manage analyze information" as ManageAnalyze
}

a -- ManageAccount
aa -- ManageAccount
ManageAccount - s
ManageAccount -- t

a -- ManageAuthorization
a -- ManageProfile

aa -- ManageAnalyze
aa -- ManageAnnouncement
aa -- ManageProject
aa -- ManageProfile
aa -- ManageScore

ManageProfile -- s
ManageRegistered -- s

ManageAnnouncement -- t
ManageProject -- t
ManageProfile -- t
ManageScore -- t






@enduml