@startuml ManageAnnouncement

skin rose
left to right direction

actor "Academic Affair" as aa
actor "Teacher" as t
actor "Student" as s

rectangle "Manage announcement" {
    usecase "Create announcement" as createAnnouncement
    usecase "View announcement info" as viewAnnouncementInfo
    usecase "Update announcement" as updateAnnouncement
    usecase "Delete announcement" as deleteAnnouncement
    
    usecase "Search announcement" as searchAnnouncement
}

aa -- createAnnouncement
aa -- viewAnnouncementInfo
aa -- updateAnnouncement
aa -- deleteAnnouncement
createAnnouncement -- t
viewAnnouncementInfo -- t
updateAnnouncement -- t
deleteAnnouncement -- t
viewAnnouncementInfo -- s

aa -- searchAnnouncement
searchAnnouncement -- t
s -- searchAnnouncement

@enduml