@startuml ManageAnnouncement

skin rose
left to right direction

actor "Academic Affair" as aa
actor "Teacher" as t
actor "Student" as s

rectangle "Manage announcement" {
    usecase "Create announcement" as createAnnouncement
    usecase "View announcement list" as ViewAnnouncementList
    usecase "View announcement detail" as viewAnnouncementDetail
    usecase "Update announcement" as updateAnnouncement
    usecase "Delete announcement" as deleteAnnouncement
    usecase "Search announcement" as searchAnnouncement
}

aa -- createAnnouncement
aa -- ViewAnnouncementList
aa -- updateAnnouncement
aa -- deleteAnnouncement
createAnnouncement -- t
ViewAnnouncementList -- t
updateAnnouncement -- t
deleteAnnouncement -- t
ViewAnnouncementList -- s

aa -- searchAnnouncement
searchAnnouncement -- t
s -- searchAnnouncement

ViewAnnouncementList <. viewAnnouncementDetail: <<extend>>
searchAnnouncement .> ViewAnnouncementList: <<include>>
@enduml