@startuml ManageAnalyzeAndReportInfo
skin rose
left to right direction
actor "Academic affair" as aff
rectangle "Manage analyze&report information" {
  usecase "View analyze" as ViewAnalyze
  usecase "Export report" as ExportReport
}
aff -- ViewAnalyze
ExportReport .up.> ViewAnalyze: <<extends>>
@enduml