@startuml ManageRegisterTime

skin rose
left to right direction

actor "Academic affair" as aa
actor "Teacher" as t

rectangle "Manage register time" {
    usecase "Create register time" as createRegisterTime
    usecase "View register time" as viewRegisterTime
    usecase "Delete register time" as deleteRegisterTime
}

aa -- createRegisterTime
aa -- viewRegisterTime
aa -- deleteRegisterTime
createRegisterTime -- t
viewRegisterTime -- t
deleteRegisterTime -- t

@enduml