@startuml ManageScore

skin rose
left to right direction

actor "Academic affair" as aa
actor "Teacher" as t


rectangle "Manage score" as ms {
    usecase "Update student score" as updateStudentScore
    usecase "Mark project score" as markProjectScore
    usecase "Export score table" as exportScoreTable
    usecase "View student score" as viewStudentScore
    usecase "View project information" as viewProjectInfo
}

aa -- viewStudentScore
aa -- exportScoreTable


viewStudentScore -- t
updateStudentScore -- t
exportScoreTable -- t
markProjectScore -- t
viewProjectInfo <.. markProjectScore: <<include>>


@enduml
