@startuml ManageAccount
skin rose
left to right direction
actor Admin
rectangle "Manage Account" as manageAccount {
    usecase "Create Account" as createAccount
    usecase "View Account" as viewAccount
    usecase "Update Account" as updateAccount
    usecase "Delete Account" as deleteAccount
    usecase "Add new class" as addNewClass
}

Admin -- createAccount
Admin -- updateAccount
Admin -- deleteAccount
Admin -- viewAccount

createAccount <.. addNewClass :  <<extends>>

@enduml