@startuml ManageRegisterTime

skin rose
left to right direction

actor "Academic affair" as aa

rectangle "Manage register time" {
    usecase "Create register time" as createRegisterTime
    usecase "View register time info" as viewRegisterTime
    usecase "Update register time" as updateRegisterTime
    usecase "Delete register time" as deleteRegisterTime
}

aa -- createRegisterTime
aa -- viewRegisterTime
aa -- deleteRegisterTime
aa -- updateRegisterTime

@enduml