@startuml Class Diagram

skin rose
skinparam classAttributeIconSize 0
' skinparam linetype ortho
skinparam linetype polyline
hide circle

class Account {
    - username
    - password

    + get()
    + update()
}

class User {
    # email
    # name
    # dateOfBirth

    + get()
    + update()
}

class Authentication {
    + login()
    + logout()
    + register()
}

class AcademicAffair {
    - academicAffairCode
    - faculty
    - position

    + get()
    + update()
}

class Student {
    - studentCode
    - class
    - major
    - status

    + get()
    + update()
}

class Teacher {
    - teacherCode
    - faculty

    + get()
    + update()
}

class Announcement {
    - title
    - content
    - dateCreated
    - dateUpdated
    - author
    - status

    + get()
    + update()
}

class Report {
    - title
    - content
    - dateCreated
    - dateUpdated
    - author

    + get()
    + update()
}

class Project {
    - name
    - teacher
    - requirement
    - maxStudentNumber
    - type
    - status
    - faculty

    + get()
    + update()
}

class ManageProject {
    + createProject()
    + getProject()
    + updateProject()
    + deleteProject()
}

class ManageProjectTeacher {
    + createCustomProject()
    + getCustomProject()
    + updateCustomProject()
    + deleteCustomProject()
    + updateProjectRequirement()
}

class Implementation {
    - student
    - project
    - score
    - status

    + get()
    + update()
}

class Register {
    + registerProject()
}

class ManageScore {
    + getScore()
    + updateScore()
    + submitScore()
}

class ManageReport {
    + createReport()
    + getReport()
    + updateReport()
    + deleteReport()
}

class ManageAnnouncement {
    + createAnnouncement()
    + getAnnouncement()
    + updateAnnouncement()
    + deleteAnnouncement()
}

Account -- User
(Account, User) .. Authentication
Student  -up-^ User
User ^-right- Teacher
User ^-left- AcademicAffair
Project -up- Implementation
Student -down- Implementation
(Student, Implementation) .. Register
AcademicAffair -left- Announcement
AcademicAffair -up- Report
AcademicAffair ---- Project
(AcademicAffair, Project) .... ManageProject
Teacher ---- Project
(Teacher, Project) .... ManageProjectTeacher
(Teacher, Implementation) .... ManageScore
ManageReport .. (AcademicAffair, Report)
(AcademicAffair, Announcement) .. ManageAnnouncement
@enduml