@startuml ClassDiagram
skin rose
skinparam classAttributeIconSize 0
' skinparam linetype ortho
skinparam linetype polyline
hide circle
scale 3

class Account {
    - username
    - password
    - role
    - userID

    + get()
    + set()
    + {static} getAccountByID()
    + {static} createAccount()
    + {static} updateAccount()
    + {static} deleteAccount()
}

class User {
    # email
    # name
    # dateOfBirth
    # phone

    + get()
    + set()
    + {static} getUserByID()
    + {static} updateUserByID()
}

class AcademicAffair {
    - academicAffairCode
    - faculty
    - userID

    + get()
    + set()
    + {static} createAA()
    + {static} getAAByID()
    + {static} getAAList()
    + {static} updateAA()
    + {static} deleteAA()

}

class Student {
    - studentCode
    - major
    - status
    - userID
    - classID

    + get()
    + set()
    + {static} getStudentList()
    
}

class Teacher {
    - teacherCode
    - faculty
    - academicDegree
    - userID

    + get()
    + set()
    + {static} getTeacherList()
}

class ClassInfo {
    - className

    +get()
    +set()
    + {static} getAllClass()
}

class Announcement {
    - title
    - content
    - dateCreated
    - dateUpdated
    - isPublic

    + get()
    + set()
    + {static} getAnnouncementList()
    + {static} createAnnouncement()
    + {static} updateAnnouncement()
    + {static} deleteAnnouncement()
    + {static} getAnnouncementByID()
}

class Project {
    - name
    - teacherID
    - requirement
    - maxStudentNumber
    - type
    - faculty
    - major
    - classID
    - isPublic
    - isRegistered
    - registerTimeID

    + get()
    + set()
    + {static} createProject()
    + {static} getProjectList()
    + {static} isProjectValid()
    + {static} deleteProject()
    + {static} updateProject()
    + {static} getProjectByID()
    + {static} setProjectTime()
}

class Implementation {
    - student1ID
    - project2ID
    - projectID
    - score
    - isCompleted
    - submissionLink

    + get()
    + set()
    + {static}  getScoreList()
    + {static}  getScoreByID()
    + {static}  updateScore()
}

class RegisterTime {
    - start
    - end
    - faculty
    - year
    - semester

    + get()
    + set()
    + {static} getAllTime()
    + {static} createTime()
    + {static} updateTime()
    + {static} deleteTime()
}

Account "1" -down- "1" User
User <|-down- Student
User <|-- Teacher
User <|-- AcademicAffair
Student "1" *-down- "*" Implementation
Student "*" -down- "1" ClassInfo
Implementation "1" -down-* "1" Project
ClassInfo "1" -down- "*" Project
Teacher "1" *-down- "*" Project
Project "*" -right- "1" RegisterTime
AcademicAffair "*" -down- "*" Announcement
AcademicAffair "*" -- "*" Project
Teacher "*" -- "*" Announcement
@enduml